version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/config/:/etc/nginx/conf.d
      - ./docker/nginx/log/:/var/log/nginx
      - ./app/:/var/www
    depends_on:
      - php
  php: 
    build:
      context: ./
      dockerfile: ./docker/php/php-fpm.dockerfile
    volumes:
      - ./app/:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8888:80"
    restart: always
    environment:
      - "PMA_HOST=mysql"
      - "PMA_PORT=3306"
    depends_on:
      - mysql


volumes:
  mysql_data:

