version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/config/:/etc/nginx/conf.d
      - ./docker/nginx/log/:/var/log/nginx
      - ./app/:/var/www
    depends_on:
      - php
  php: 
    build:
      context: ./
      dockerfile: ./docker/php/php-fpm.dockerfile
    volumes:
      - ./app/:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "33061:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:

